print ('hello word')
numero = int (input ('digite un numero para ver sua tabuada') )
print ( '{} x {} = {}'.format (numero , 1 , numero*1 ))
print ( '{} x {} = {}'.format (numero , 2 , numero*2 ))
print ( '{} x {} = {}'.format (numero , 3 , numero*3 ))
print ( '{} x {} = {}'.format (numero , 4 , numero*4 ))
print ( '{} x {} = {}'.format (numero , 5 , numero*5 ))
print ( '{} x {} = {}'.format (numero , 6 , numero*6 ))
print ( '{} x {} = {}'.format (numero , 7 , numero*7 ))
print ( '{} x {} = {}'.format (numero , 8 , numero*8 ))
print ( '{} x {} = {}'.format (numero , 9 , numero*9 ))
print ( '{} x {} = {}'.format (numero , 10 , numero*10 ))
# ('fiquei meia hora fazendo isso so pra colocar um vezes no final' * 12)
print ( '{} x {} = {}'.format (numero , 11 , numero*11 ))
print ( '{} x {} = {}'.format (numero , 12 , numero*12))
print ( '{} x {} = {}'.format (numero , 13 , numero*13))
print ( '{} x {} = {}'.format (numero , 14 , numero*14))
print ( '{} x {} = {}'.format (numero , 15 , numero*15))
print ( '{} x {} = {}'.format (numero , 16 , numero*16))
print ( '{} x {} = {}'.format (numero , 17 , numero*17))
print ( '{} x {} = {}'.format (numero , 18 , numero*18))
print ( '{} x {} = {}'.format (numero , 19 , numero*19))
print ( '{} x {} = {}'.format ( numero , 20 , numero*20))
#veigh baby 
